/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorksRouteImport } from './routes/works'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioWorkIdRouteImport } from './routes/studio/$workId'
import { Route as ApiRetryFailedRouteImport } from './routes/api/retry-failed'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiWorkImagesImageIdRouteImport } from './routes/api/work-images/$imageId'

const WorksRoute = WorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioWorkIdRoute = StudioWorkIdRouteImport.update({
  id: '/studio/$workId',
  path: '/studio/$workId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRetryFailedRoute = ApiRetryFailedRouteImport.update({
  id: '/api/retry-failed',
  path: '/api/retry-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkImagesImageIdRoute = ApiWorkImagesImageIdRouteImport.update({
  id: '/api/work-images/$imageId',
  path: '/api/work-images/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/works': typeof WorksRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/retry-failed': typeof ApiRetryFailedRoute
  '/studio/$workId': typeof StudioWorkIdRoute
  '/studio/': typeof StudioIndexRoute
  '/api/work-images/$imageId': typeof ApiWorkImagesImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/works': typeof WorksRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/retry-failed': typeof ApiRetryFailedRoute
  '/studio/$workId': typeof StudioWorkIdRoute
  '/studio': typeof StudioIndexRoute
  '/api/work-images/$imageId': typeof ApiWorkImagesImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/works': typeof WorksRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/retry-failed': typeof ApiRetryFailedRoute
  '/studio/$workId': typeof StudioWorkIdRoute
  '/studio/': typeof StudioIndexRoute
  '/api/work-images/$imageId': typeof ApiWorkImagesImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/works'
    | '/api/generate'
    | '/api/retry-failed'
    | '/studio/$workId'
    | '/studio/'
    | '/api/work-images/$imageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/works'
    | '/api/generate'
    | '/api/retry-failed'
    | '/studio/$workId'
    | '/studio'
    | '/api/work-images/$imageId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/works'
    | '/api/generate'
    | '/api/retry-failed'
    | '/studio/$workId'
    | '/studio/'
    | '/api/work-images/$imageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  WorksRoute: typeof WorksRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiRetryFailedRoute: typeof ApiRetryFailedRoute
  StudioWorkIdRoute: typeof StudioWorkIdRoute
  StudioIndexRoute: typeof StudioIndexRoute
  ApiWorkImagesImageIdRoute: typeof ApiWorkImagesImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/works': {
      id: '/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof WorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$workId': {
      id: '/studio/$workId'
      path: '/studio/$workId'
      fullPath: '/studio/$workId'
      preLoaderRoute: typeof StudioWorkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/retry-failed': {
      id: '/api/retry-failed'
      path: '/api/retry-failed'
      fullPath: '/api/retry-failed'
      preLoaderRoute: typeof ApiRetryFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/work-images/$imageId': {
      id: '/api/work-images/$imageId'
      path: '/api/work-images/$imageId'
      fullPath: '/api/work-images/$imageId'
      preLoaderRoute: typeof ApiWorkImagesImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  WorksRoute: WorksRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiRetryFailedRoute: ApiRetryFailedRoute,
  StudioWorkIdRoute: StudioWorkIdRoute,
  StudioIndexRoute: StudioIndexRoute,
  ApiWorkImagesImageIdRoute: ApiWorkImagesImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
